language: node_js
node_js:
- 14
services:
- docker
cache:
  yarn: true
  directories:
  - node_modules
script:
- docker build --pull -t "${IMAGE_NAME}" .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
- docker push "${IMAGE_NAME}"
notifications:
  slack:
    rooms:
    - araytek:B8Xevy6shC51ftn3tBiZR8fw
    on_success: change
    on_failure: always
branches:
  only:
  - master
  - "/^greenkeeper.*$/"
env:
  global:
  - secure: FPkcAC5yS1E8dIIDG5gAT2wUFnbn6XEOldDGRx3wwKHT4tTwQlxZ9iEUPJF9CVIUhaNIvRf5HnGNW08gPdbXfx0YTdttyZlmno4sIqA3Hl4/PwI7AfCn49LCbtvdWYOoH+Fd8T1f2moa78nf7icmfqUHJZcAee3zleCpSuufdEoSjAAKaH4jG9vTggI0mtTNI8Tpfx2NPBbKtVh/DrEV/DOYaJ7oHsFs7yi2tDMpfXd+YPZqcuDK+Yi6EvH8fE21O2XCUwQCcyBDqobaLl+rdo11YClHr+V8ciTIS5hiwxZJDB9g+MeDz3C5/XGdRVgFJCUmztEzbPEdi5pRkNmhgmY2LcLdnxNei6L0rkuDwBxxHuuZcUAqWQ7ye9LL2SVHnShRizWB2OmTIzUEpWUzTUoKMXaFDKAmozqYjHTapt9Y/A8BjFJY1Tt8v8QO1Mm6XVQCE2M91suWkmv4aj+ps6I1ORZuEPryo6nbsoyAL+1z+zSwYA1etWIFMXqqUZ2n85sKQuPh62IhSIx4ZIJ79KYxlsIVbPamws1DFEL5BAOOT7tCg9Nb0ZlgT1Kek3x03PWqThQg0/rxpp6cbZ460QQ1LsS4ABM9kDo5by6Uuqpl9OZMAdmqyp44UmGwH/bjfKH6t3cnZchWjLaHVoiW8TKE5wMmQhZPkbdskX7bPmw=
  - PROJECT_NAME: osk2/ptt-comment-flag
  - IMAGE_NAME: "${PROJECT_NAME}:${TRAVIS_COMMIT:0:8}"
